language: python
python:
  - "3.8"

services:
  - postgresql

before_install:
  - cp .env.example .env

install:
  - pip install pipenv
  - pipenv install --dev

env:
  - DJANGO_SETTINGS_MODULE="config.settings.test"

before_script:
  - psql -c 'create database db_test;' -U postgres

script:
  - coverage run -a --source=".." -m pytest -vv
